name: sfm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - libffi=3.2.1
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.7.6
  - python_abi=3.7
  - setuptools=49.6.0
  - sqlite=3.35.2
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - addict==2.4.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cached-property==1.5.2
    - cffi==1.14.5
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - entrypoints==0.3
    - h5py==3.2.1
    - importlib-metadata==3.8.0
    - ipykernel==5.5.0
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.4.0
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - networkx==2.5
    - notebook==6.3.0
    - numpy==1.20.1
    - open3d==0.12.0
    - opencv-python==4.5.1.48
    - packaging==20.9
    - pandas==1.2.3
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.2
    - plyfile==0.7.3
    - pptk==0.1.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.8.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - scikit-learn==0.24.1
    - scipy==1.6.2
    - send2trash==1.5.0
    - six==1.15.0
    - sklearn==0.0
    - terminado==0.9.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - torch==1.8.1
    - tornado==6.1
    - tqdm==4.59.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.1